# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'VideoEditDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VideoEditDemo
  pod 'MBProgressHUD', '~> 1.1.0'

end
